import { toast } from "./ui.js";
const $=id=>document.getElementById(id);
let currentReviews=[];
const stars=r=>"★".repeat(Number(r)||5)+"☆".repeat(5-(Number(r)||5));
const plural=n=>{const a=n%10,b=n%100;return a===1&&b!==11?"отзыв":a>=2&&a<=4&&(b<12||b>14)?"отзыва":"отзывов"};
const likedKey="appcore_review_liked_";
const date=v=>{try{return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v))}catch{return""}};

function renderSummary(rs){const box=$("ratingSummary");if(!rs.length){box.hidden=true;return}const n=rs.length,c=[0,0,0,0,0,0];rs.forEach(r=>c[r]++);const avg=rs.reduce((a,b)=>a+b,0)/n;$("ratingAvg").textContent=avg.toFixed(1).replace(".",",");$("ratingStars").textContent=stars(Math.round(avg));$("ratingCount").textContent=n+" "+plural(n);const bars=$("ratingBars");bars.replaceChildren();for(let s=5;s>0;s--){const row=document.createElement("div");row.className="bar-row";row.innerHTML='<span class="bar-label">'+s+' ★</span><div class="bar-track"><div class="bar-fill" style="width:'+Math.round(c[s]/n*100)+'%"></div></div><span class="bar-pct">'+Math.round(c[s]/n*100)+'%</span>';bars.append(row)}box.hidden=false}
function dots(){const d=$("reviewDots");d.replaceChildren(...currentReviews.map((_,i)=>{const x=document.createElement("span");x.className="review-dot"+(i?"":" active");return x}))}
function setDot(i){[...document.querySelectorAll(".review-dot")].forEach((x,n)=>x.classList.toggle("active",n===i))}
function updateHomepageCard(r,i){const cardEl=document.querySelectorAll(".review")[i];if(!cardEl)return;const meta=cardEl.querySelector(".review-meta");if(!meta)return;meta.replaceChildren();meta.append(document.createTextNode((r.author||"Клиент")+" · "+date(r.created_at)));if(Number(r.likes||0)){meta.append(document.createTextNode(" · "));const like=document.createElement("b");like.className="review-like-mini";like.textContent="❤️ "+Number(r.likes||0);meta.append(like)}}
function createLikeButton(r,i){const like=document.createElement("button");like.type="button";like.className="all-review-like";like.dataset.reviewIndex=String(i);const liked=localStorage.getItem(likedKey+r.id)==="1";like.disabled=liked;like.setAttribute("aria-pressed",liked?"true":"false");const heart=document.createElement("span");heart.className="heart";heart.textContent="❤️";const label=document.createElement("span");label.className="all-review-like-label";label.textContent=liked?"Понравилось":"Нравится";const count=document.createElement("span");count.className="all-review-like-count";count.textContent=String(Number(r.likes||0));like.append(heart,label,count);return like}
function renderAllReviews(){const list=$("allReviewsList");if(!list)return;if(!currentReviews.length){const n=document.createElement("div");n.className="note";n.textContent="Пока нет отзывов";list.replaceChildren(n);return}list.replaceChildren(...currentReviews.map((r,i)=>{const article=document.createElement("article");article.className="all-review-item";const top=document.createElement("div");top.className="all-review-top";const author=document.createElement("strong");author.textContent=r.author||"Клиент";const d=document.createElement("span");d.textContent=date(r.created_at);top.append(author,d);const st=document.createElement("div");st.className="all-review-stars";st.textContent=stars(r.rating);const text=document.createElement("div");text.className="all-review-text";text.textContent=r.text||"";article.append(top,st,text);if(r.admin_reply){const reply=document.createElement("div");reply.className="all-review-reply";const title=document.createElement("strong");title.textContent="💬 Ответ администрации";const body=document.createElement("div");body.textContent=r.admin_reply;reply.append(title,body);article.append(reply)}article.append(createLikeButton(r,i));return article}))}
function openAllReviews(){if(!currentReviews.length)return;renderAllReviews();const modal=$("reviewDetailModal");modal.classList.add("show");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");$("reviewDetailClose")?.focus()}
function closeDetail(){const modal=$("reviewDetailModal");modal.classList.remove("show");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
function card(r,i){const e=document.createElement("button");e.type="button";e.className="review";e.dataset.reviewIndex=String(i);e.setAttribute("aria-label","Открыть все отзывы");const st=document.createElement("div");st.className="stars";st.textContent=stars(r.rating);const p=document.createElement("p");p.textContent=r.text||"";const meta=document.createElement("span");meta.className="review-meta";meta.append(document.createTextNode((r.author||"Клиент")+" · "+date(r.created_at)));if(Number(r.likes||0)){meta.append(document.createTextNode(" · "));const like=document.createElement("b");like.className="review-like-mini";like.textContent="❤️ "+Number(r.likes||0);meta.append(like)}e.append(st,p,meta);if(r.admin_reply){const reply=document.createElement("div");reply.className="review-reply-mini";const title=document.createElement("strong");title.textContent="💬 Ответ администрации";const body=document.createElement("span");body.textContent=r.admin_reply;reply.append(title,body);e.append(reply)}return e}
async function loadReviews(sb){const slider=$("reviewsSlider");try{const {data,error}=await sb.from("reviews").select("id,author,rating,text,created_at,admin_reply,likes,is_pinned").eq("status","approved").order("created_at",{ascending:false}).limit(50);if(error)throw error;currentReviews=(data||[]).sort((a,b)=>Number(b.is_pinned)-Number(a.is_pinned)||Number(b.rating)-Number(a.rating)||Number(b.likes)-Number(a.likes)||new Date(b.created_at)-new Date(a.created_at));renderSummary(currentReviews.map(r=>Number(r.rating)));slider.replaceChildren(...(currentReviews.length?currentReviews.map(card):[(()=>{const n=document.createElement("div");n.className="note";n.textContent="Пока нет отзывов — станьте первым!";return n})()]));dots();slider.onscroll=()=>{if(currentReviews.length)setDot(Math.max(0,Math.min(currentReviews.length-1,Math.round(slider.scrollLeft/(slider.clientWidth+10)))))};}catch(e){console.error(e);slider.replaceChildren((()=>{const n=document.createElement("div");n.className="note";n.textContent="Не удалось загрузить отзывы";return n})())}}
function initDetail(sb){const modal=$("reviewDetailModal"),close=$("reviewDetailClose"),slider=$("reviewsSlider"),list=$("allReviewsList");if(!modal||!close||!slider||!list)return;slider.addEventListener("click",e=>{if(e.target.closest(".review"))openAllReviews()});close.onclick=closeDetail;modal.onclick=e=>{if(e.target===modal)closeDetail()};list.addEventListener("click",async e=>{const like=e.target.closest(".all-review-like");if(!like||like.disabled)return;const i=Number(like.dataset.reviewIndex),r=currentReviews[i];if(!r)return;like.disabled=true;try{const {data,error}=await sb.rpc("like_review",{p_review_id:r.id});if(error)throw error;r.likes=Number(data||r.likes||0);localStorage.setItem(likedKey+r.id,"1");like.setAttribute("aria-pressed","true");like.querySelector(".all-review-like-label").textContent="Понравилось";like.querySelector(".all-review-like-count").textContent=String(r.likes);updateHomepageCard(r,i)}catch(err){console.error(err);like.disabled=false}});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("show"))closeDetail()})}
function initForm(sb){const m=$("reviewModal"),f=$("reviewForm"),sp=[...document.querySelectorAll("#starPick button")];let rating=5;const paint=()=>sp.forEach((b,i)=>b.classList.toggle("on",i<rating));sp.forEach((b,i)=>b.onclick=()=>{rating=i+1;paint()});paint();$("reviewOpen").onclick=()=>m.classList.add("show");$("reviewClose").onclick=()=>m.classList.remove("show");m.onclick=e=>{if(e.target===m)m.classList.remove("show")};f.onsubmit=async e=>{e.preventDefault();const author=f.elements.author.value.trim()||"Клиент",text=f.elements.text.value.trim();if(text.length<10)return toast("Напишите хотя бы 10 символов");const b=f.querySelector("[type=submit]");b.disabled=true;try{const {error}=await sb.rpc("submit_review",{p_author:author.slice(0,40),p_rating:rating,p_text:text.slice(0,500)});if(error)throw error;f.reset();rating=5;paint();m.classList.remove("show");toast("Спасибо! Отзыв опубликован");await loadReviews(sb)}catch(err){console.error(err);toast("Не удалось отправить отзыв. Попробуйте ещё раз")}finally{b.disabled=false}}}
export function initReviews(sb){loadReviews(sb);initForm(sb);initDetail(sb)}
