import { toast } from "./ui.js";
const $=id=>document.getElementById(id);let currentReviews=[],currentIndex=0;
const stars=r=>"★".repeat(Number(r)||5)+"☆".repeat(5-(Number(r)||5));
const plural=n=>{const a=n%10,b=n%100;return a===1&&b!==11?"отзыв":a>=2&&a<=4&&(b<12||b>14)?"отзыва":"отзывов"};
const date=v=>{try{return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(v))}catch{return""}};
function renderSummary(rs){const box=$("ratingSummary");if(!rs.length){box.hidden=true;return}const n=rs.length,c=[0,0,0,0,0,0];rs.forEach(r=>c[r]++);const avg=rs.reduce((a,b)=>a+b,0)/n;$("ratingAvg").textContent=avg.toFixed(1).replace(".",",");$("ratingStars").textContent=stars(Math.round(avg));$("ratingCount").textContent=n+" "+plural(n);const bars=$("ratingBars");bars.replaceChildren();for(let s=5;s>0;s--){const row=document.createElement("div");row.className="bar-row";row.innerHTML='<span class="bar-label">'+s+' ★</span><div class="bar-track"><div class="bar-fill" style="width:'+Math.round(c[s]/n*100)+'%"></div></div><span class="bar-pct">'+Math.round(c[s]/n*100)+'%</span>';bars.append(row)}box.hidden=false}
function dots(){const d=$("reviewDots");d.replaceChildren(...currentReviews.map((_,i)=>{const x=document.createElement("span");x.className="review-dot"+(i?"":" active");return x}))}
function setDot(i){[...document.querySelectorAll(".review-dot")].forEach((x,n)=>x.classList.toggle("active",n===i))}
function openDetail(i){if(!currentReviews.length)return;currentIndex=(i+currentReviews.length)%currentReviews.length;const r=currentReviews[currentIndex];$("detailStars").textContent=stars(r.rating);$("detailAuthor").textContent=r.author||"Клиент";$("detailDate").textContent=date(r.created_at);$("detailText").textContent=r.text||"";$("reviewPosition").textContent=currentIndex+1+" / "+currentReviews.length;$("reviewDetailModal").classList.add("show")}
function closeDetail(){$("reviewDetailModal").classList.remove("show")}
function card(r,i){const e=document.createElement("button");e.type="button";e.className="review";e.innerHTML='<div class="stars">'+stars(r.rating)+'</div><p></p><span></span>';e.querySelector("p").textContent=r.text||"";e.querySelector("span").textContent=(r.author||"Клиент")+" · "+date(r.created_at);e.onclick=()=>openDetail(i);return e}
async function loadReviews(sb){const slider=$("reviewsSlider");try{const {data,error}=await sb.from("reviews").select("id,author,rating,text,created_at").eq("status","approved").order("created_at",{ascending:false}).limit(50);if(error)throw error;currentReviews=(data||[]).sort((a,b)=>Number(b.rating)-Number(a.rating)||new Date(b.created_at)-new Date(a.created_at));renderSummary(currentReviews.map(r=>Number(r.rating)));slider.replaceChildren(...(currentReviews.length?currentReviews.map(card):[(()=>{const n=document.createElement("div");n.className="note";n.textContent="Пока нет отзывов — станьте первым!";return n})()]));dots();slider.onscroll=()=>{if(currentReviews.length)setDot(Math.max(0,Math.min(currentReviews.length-1,Math.round(slider.scrollLeft/(slider.clientWidth+10)))))};}catch(e){console.error(e);slider.replaceChildren((()=>{const n=document.createElement("div");n.className="note";n.textContent="Не удалось загрузить отзывы";return n})())}}
function initDetail(){$("reviewDetailClose").onclick=closeDetail;$("reviewDetailModal").onclick=e=>{if(e.target===$("reviewDetailModal"))closeDetail()};$("reviewPrev").onclick=()=>openDetail(currentIndex-1);$("reviewNext").onclick=()=>openDetail(currentIndex+1);let sx=0;$("reviewDetailCard").ontouchstart=e=>sx=e.changedTouches[0].clientX;$("reviewDetailCard").ontouchend=e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)openDetail(currentIndex+(dx<0?1:-1))}}
function initForm(sb){const m=$("reviewModal"),f=$("reviewForm"),sp=[...document.querySelectorAll("#starPick button")];let rating=5;const paint=()=>sp.forEach((b,i)=>b.classList.toggle("on",i<rating));sp.forEach((b,i)=>b.onclick=()=>{rating=i+1;paint()});paint();$("reviewOpen").onclick=()=>m.classList.add("show");$("reviewClose").onclick=()=>m.classList.remove("show");m.onclick=e=>{if(e.target===m)m.classList.remove("show")};f.onsubmit=async e=>{e.preventDefault();const author=f.elements.author.value.trim()||"Клиент",text=f.elements.text.value.trim();if(text.length<10)return toast("Напишите хотя бы 10 символов");const b=f.querySelector("[type=submit]");b.disabled=true;try{const {error}=await sb.from("reviews").insert([{author:author.slice(0,40),rating,text:text.slice(0,500),status:"pending"}]);if(error)throw error;f.reset();rating=5;paint();m.classList.remove("show");toast("Спасибо! Отзыв отправлен на проверку")}catch(err){console.error(err);toast("Не удалось отправить отзыв. Попробуйте ещё раз")}finally{b.disabled=false}}}
export function initReviews(sb){loadReviews(sb);initForm(sb);initDetail()}