(function(){
"use strict";
const URL="https://dkgipfotfjntlhabakns.supabase.co";
const KEY="sb_publishable_Yqtu6SOTncAsze5_whAAFQ_KjTUbK_6";
const SESSION_KEY="appcore_admin_session";
function readSession(){try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const s=JSON.parse(raw);return s&&s.access_token?s:null;}catch(e){return null;}}
function saveSession(s){try{if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY);}catch(e){}}
async function request(path,options){const s=readSession();const headers=Object.assign({"apikey":KEY,"Content-Type":"application/json"},options&&options.headers||{});if(s&&s.access_token)headers.Authorization="Bearer "+s.access_token;const res=await fetch(URL+path,Object.assign({},options,{headers}));const raw=await res.text();let data=null;try{data=raw?JSON.parse(raw):null;}catch(e){}if(!res.ok)return{data:null,error:{message:(data&&(data.msg||data.message||data.error_description||data.error))||("HTTP "+res.status),status:res.status}};return{data,error:null};}
async function refresh(){const s=readSession();if(!s||!s.refresh_token)return null;const body=new URLSearchParams({grant_type:"refresh_token",refresh_token:s.refresh_token});const res=await fetch(URL+"/auth/v1/token?grant_type=refresh_token",{method:"POST",headers:{"apikey":KEY,"Content-Type":"application/x-www-form-urlencoded"},body});const data=await res.json().catch(()=>null);if(!res.ok||!data||!data.access_token){saveSession(null);return null;}saveSession(data);return data;}
function createClient(){return{auth:{async signInWithPassword({email,password}){const res=await fetch(URL+"/auth/v1/token?grant_type=password",{method:"POST",headers:{"apikey":KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await res.json().catch(()=>null);if(!res.ok||!data||!data.access_token)return{data:null,error:{message:(data&&(data.error_description||data.msg||data.message))||"Неверный email или пароль."}};saveSession(data);return{data:{session:data,user:data.user},error:null};},async getSession(){let s=readSession();if(!s)return{data:{session:null},error:null};const exp=Number(s.expires_at||0);if(exp&&exp*1000<Date.now()+30000)s=await refresh();return{data:{session:s},error:null};},async signOut(){const s=readSession();if(s&&s.access_token){try{await fetch(URL+"/auth/v1/logout",{method:"POST",headers:{"apikey":KEY,"Authorization":"Bearer "+s.access_token}});}catch(e){}}saveSession(null);return{error:null};}},from(table){let select="*";let orderBy=null;let ascending=true;const builder={select(value="*"){select=value;return builder;},order(column,opts={}){orderBy=column;ascending=opts.ascending!==false;return builder;},then(resolve,reject){let path="/rest/v1/"+encodeURIComponent(table)+"?select="+encodeURIComponent(select);if(orderBy)path+="&order="+encodeURIComponent(orderBy)+"."+(ascending?"asc":"desc");request(path).then(resolve,reject);}};return builder;},rpc(functionName,params){return request("/rest/v1/rpc/"+encodeURIComponent(functionName),{method:"POST",body:JSON.stringify(params||{})});},channel(){return{on(){return this;},subscribe(cb){if(cb)cb("SUBSCRIBED");return this;}};},async removeChannel(){return null;}};}
if(!window.supabase)window.supabase={createClient};
})();